// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmCQb_Qv3iy6kvMM6Oo68Jd8U7URA0nA',
    appId: '1:715182306359:web:c7996fe9a94bf1f0c5fbb2',
    messagingSenderId: '715182306359',
    projectId: 'ams-ml-project',
    authDomain: 'ams-ml-project.firebaseapp.com',
    storageBucket: 'ams-ml-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_r4dNbRcfPYd73MqInMvr2wibEFJo_GA',
    appId: '1:715182306359:android:1c40dd6abde3bcb7c5fbb2',
    messagingSenderId: '715182306359',
    projectId: 'ams-ml-project',
    storageBucket: 'ams-ml-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZQoUiGiOgduaWCRuM4qS-piv6HSmbIA',
    appId: '1:715182306359:ios:ab1098ec9445407fc5fbb2',
    messagingSenderId: '715182306359',
    projectId: 'ams-ml-project',
    storageBucket: 'ams-ml-project.firebasestorage.app',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAZQoUiGiOgduaWCRuM4qS-piv6HSmbIA',
    appId: '1:715182306359:ios:ab1098ec9445407fc5fbb2',
    messagingSenderId: '715182306359',
    projectId: 'ams-ml-project',
    storageBucket: 'ams-ml-project.firebasestorage.app',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkmCQb_Qv3iy6kvMM6Oo68Jd8U7URA0nA',
    appId: '1:715182306359:web:b4000f51988c37f3c5fbb2',
    messagingSenderId: '715182306359',
    projectId: 'ams-ml-project',
    authDomain: 'ams-ml-project.firebaseapp.com',
    storageBucket: 'ams-ml-project.firebasestorage.app',
  );
}
